version: '3'
services:
  bot:
    build: .
    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dexon
      - POSTGRES_DB=postgres
    ports:
      - '5432:5432'
    container_name: aiogrambot3
    volumes:
      - .:/app
    command: hupper -m main
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Dexon
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  redis:
    image: redis
    env_file:
      - .env
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
  redis2:
    image: redis
    env_file:
      - .env
    volumes:
      - redis2_data:/data
    ports:
      - "6380:6379"


volumes:
  postgres_data:
  redis_data:
  redis2_data:
